version: '3.9'

services:
  db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "my_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"